book_review3/apps/reviews/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^register$', views.register),
    url(r'^success$', views.success),
    url(r'^log_user_in$', views.log_user_in),
    url(r'^print_messages$', views.print_messages),
    url(r'^logout$', views.logout),
    url(r'^add_book$', views.add_book),
    url(r'^add_book_review$', views.add_book_review),
    url(r'^create_book$', views.create_book),
    url(r'^add_review/(?P<book_id>\d+)$', views.add_review),
    url(r'^user_reviews/(?P<user_id>\d+)$', views.user_reviews),
    url(r'^append_review/(?P<book_id>\d+)$', views.append_review),
    url(r'^delete_review/(?P<review_id>\d+)$', views.delete_review),
    url(r'^destroy_review/(?P<review_id>\d+)$', views.destroy_review),
    url(r'^login$', views.login)
]

book_review3/book_review3/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.reviews.urls'))
]

book_review3/apps/reviews/models.py
from __future__ import unicode_literals
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
import bcrypt, re
import south

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

class UserManager(models.Manager):
    def validateReg(self,request):
        errors = self.validate_inputs(request)
        if errors:
            return (False,errors)
        user_list = User.objects.filter(email=request.POST['email'])
        if len(user_list)>0:
            errors.append("Email already exists")
            return (False, errors)
        else:
            pw_hash = bcrypt.hashpw(request.POST['password'].encode(), bcrypt.gensalt())

            user = self.create(first_name=request.POST['first_name'],alias=request.POST['alias'],email=request.POST['email'].lower(),pw_hash=pw_hash)
            return (True,user)


    def validateLogin(self, request):
        try:
            user = User.objects.get(email=request.POST['email'].lower())
            password = request.POST['password'].encode()

            if bcrypt.hashpw(password,user.pw_hash.encode()):
                return (True,user)
        except ObjectDoesNotExist:
            pass
        return (False,["Email/Password doesn't match"])

    def validate_inputs(self, request):
        errors = []
        if len(request.POST['first_name']) < 3 or len(request.POST['alias']) < 3:
            errors.append("Please enter a first name/alias that is longer than 2 characters")
        if not EMAIL_REGEX.match(request.POST['email']):
            errors.append("Invalid email entered")
        if len(request.POST['password']) < 8:
            errors.append("Password must be at least 8 characters")
        if len(request.POST['password']) < 8 or request.POST['password'] != request.POST['confirm_pw']:
            errors.append("Passwords must match and be at least 8 characters.")
        return errors

class BookManager(models.Manager):
    def validate_inputs(self,request):
        errors = []
        author = request.POST['author']
        if len(request.POST['title'])<1:
            errors.append("Please enter a title")
        if len(request.POST['author']) < 1:
            author = request.POST['author_list']
        if len(request.POST['review']) < 1:
            errors.append("Please enter a review")
        if errors:
            return (False,errors)
        else:
            book = {
            'user': request.session['user']['id'],
            'title' : request.POST['title'],
            'author_list' : request.POST['author_list'],
            'author' : author,
            'rating' : request.POST['rating'],
            'review' : request.POST['review']
            }
        return (True,book)


class ReviewManager(models.Manager):
    def validate_inputs(self,request):
        errors = []
        if len(request.POST['review']) < 1:
            errors.append("Please enter a review")
            return (False,errors)
        else:
            return (True,errors)


class User(models.Model):
    first_name = models.CharField(max_length=255)
    alias = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    pw_hash = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = UserManager()

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = BookManager()

class Review(models.Model):
    review = models.CharField(max_length=1000)
    rating = models.IntegerField()
    book = models.ForeignKey(Book, related_name='reviews')
    user = models.ForeignKey(User, related_name='reviews')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ReviewManager()

book_review3/apps/reviews/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User, Book, Review
# from sets import Set

# Create your views here.
def index(request):
    return render(request, 'reviews/index.html')

def register(request):
    result = User.objects.validateReg(request)
    if result[0]==False:
        print_messages(request, result[1])
        return redirect('/')
    return log_user_in(request,result[1])

def add_review(request,book_id):
    books = Book.objects.all()
    book = Book.objects.get(id=book_id)
    reviews = Review.objects.filter(book__id=book_id)
    context = {
        'books':books,
        'book':book,
        'reviews':reviews
    }
    return render(request, 'reviews/book.html',context)

def delete_review(request,review_id):
    review = Review.objects.get(id=review_id)
    context = {
        'review':review
    }
    return render(request,'reviews/delete_review.html',context)

def destroy_review(request,review_id):
    Review.objects.get(id=review_id).delete()
    return redirect('/success')

def append_review(request,book_id):
    result = Review.objects.validate_inputs(request)
    if result[0]==False:
        print_messages(request,result[1])
    else:
        book = Book.objects.get(id=book_id)
        user = User.objects.get(id=request.session['user']['id'])
        newReview = Review.objects.create(review=request.POST['review'],rating=request.POST['rating'],book=book, user=user)
    return redirect('/add_review/{}'.format(book_id))

def user_reviews(request,user_id):
    user = User.objects.get(id=user_id)
    # reviews = list(set(Review.objects.filter(user__id=user_id)))
    reviews = Review.objects.all().filter(user__id=user_id).values('book__id','book__title').distinct()

    print "REVIEWS IS =========>",reviews
    # for review in reviews:
    #     print review.review
    count = len(reviews)
    context = {
        'user':user,
        'reviews':reviews,
        'count':count,
    }
    return render(request,'reviews/user_reviews.html',context)

def success(request):
    if 'user' not in request.session:
        return redirect('/')
    review_list = Review.objects.all().order_by('-created_at')
    book_list = Book.objects.all().order_by('-created_at')[:3]
    book_list2 = Book.objects.all()
    user_list = User.objects.all()[:3]
    print book_list[0].title
    context = {
        'users': user_list,
        'books': book_list,
        'books2': book_list2,
        'reviews': review_list
    }
    return render(request, 'reviews/home.html',context)

def login(request):
    result = User.objects.validateLogin(request)

    if result[0]==False:
        print_messages(request, result[1])
        return redirect('/')
    return log_user_in(request,result[1])

def add_book_review(request):
    books = Book.objects.values('author').distinct()
    context = {
        'books':books
    }
    return render(request, 'reviews/add_book.html',context)

def multiple_book_check(request,book):
    errors = []
    review_list = Review.objects.filter(user_id=request.session['user']['id'])
    print "PRINTING LIST OF REVIEWS BY THIS USER=====>",review_list
    if len(review_list)<1:
        return (True, book)
    else:
        for review in review_list:
            if review.book.title.lower()==book['title'].lower():
                errors.append("You already wrote a review for that book")
                return (False,errors)
            else:
                return (True, book)

def add_book(request,book):
    #check if user already created a review for that book

    user = User.objects.get(id=request.session['user']['id'])
    #gets a list of books the user has reviewed
    review_list = Review.objects.filter(user_id=request.session['user']['id'])
    #check if a book title that was entered matches any of these books
    result = multiple_book_check(request,book)
    if result[0]==True:
        newBook = Book.objects.create(title=book['title'], author=book['author'])
        # print "THIS IS THE review WE JUST WROTE====>",book['review']
        newReview = Review.objects.create(review=book['review'],rating=book['rating'],book=newBook,user=user)
        print "NEW BOOK IS============",newBook
        return redirect('/success')
    else:
        print_messages(request,result[1])
        return redirect('/success')


def create_book(request):
    result = Book.objects.validate_inputs(request)
    if result[0]==True:
        print "NO ERRORS"
        print "result[1] is==========>",result[1]
        return add_book(request,result[1])
    print_messages(request,result[1])
    return redirect('/add_book_review')

def print_messages(request, message_list):
    for message in message_list:
        messages.add_message(request, messages.INFO, message)

def log_user_in(request,user):
    request.session['user'] = {
            'id':user.id,
            'first_name':user.first_name,
            'alias':user.alias,
            'email':user.email,
    }
    messages.add_message(request, messages.INFO, "successfully logged in! VALID EMAIL {}".format(user.email))
    return redirect('/success')

def logout(request):
    request.session.pop('user')
    return redirect('/')

book_review3/apps/reviews/templates/reviews/add_book.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Add Book</title>
  </head>
  <body>
    <a href="/success"><button>Home</button></a> <a href="/logout"><button>Logout</button></a>
    <h1>Add a New Book Title and Review</h1>
    {%if messages%}
      {%for message in messages%}
        {{message}}<br>
      {%endfor%}
    {%endif%}
    <form action="/create_book" method="post">
      {%csrf_token%}
      Book Title: <input type="text" name="title" value=""><br>
      Author: <br>
        &emsp; Choose from the list: <select name="author_list" value="">
            {%for book in books%}
            <option value="{{book.author}}">{{book.author}}</option>
            {%endfor%}
          </select><br>
          &nbsp&emsp;Or add a new author: <input type="text" name="author" value=""><br>
          Review: <br><textarea name="review" rows="8" cols="80"></textarea><br>
          Rating: <select name="rating" value="">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
          </select> stars<br><br>
          <input type="submit" name="" value="Add Book and Review">
    </form>
  </body>
</html>

book_review3/apps/reviews/templates/reviews/book.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Add Review</title>
  </head>
  <body>
    <h1 style='padding:0px;margin:0px'>{{book.title}}</h1>
    Author: {{book.author}}<br>
    <a href="/success"><button>Home</button></a><a href="/logout"><button>Logout</button></a>
    <h3>Add a review</h3>
    <form action="/append_review/{{book.id}}" method="post">
      {%csrf_token%}
      <textarea name="review" rows="8" cols="80"></textarea><br>
      Select Rating: <select name="rating">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
      </select>
      <input type="submit" name="" value="Add Review">
    </form>
    <h2>Reviews:</h2>
    {%for review in reviews%}
    <a href="/user_reviews/{{review.user.id}}">{{review.user.first_name}}</a> says: {{review.review}}<br>
     Rating: {{review.rating}}<br><br>
    {%endfor%}
  </body>
</html>

book_review3/apps/reviews/templates/reviews/delete_review.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>delete review</title>
  </head>
  <body>
    <h1>Are you sure you want to delete this review?</h1>
    <h3>{{review.book.title}}</h3>
    {{review.user.first_name}} says: {{review.review}}<br><br>
    <a href="/destroy_review/{{review.id}}"><button>Yes</button></a>
    <a href="/success"><button>No</button></a>
  </body>
</html>

book_review3/apps/reviews/templates/reviews/home.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Books Home</title>
  </head>
  <body>
    {%if messages %}
      {%for message in messages%}
        {{message}}
      {%endfor%}
    {%endif%}
    <h1>Welcome, {{request.session.user.first_name}}!</h1>
    <a href="/logout"><button>Log Out</button></a>
    <a href="/add_book_review"><button>Add Book and Review</button></a>

    <h2>Recent Book Reviews:</h2>
    {%for book in books%}
      <h2 style='padding:0px;margin:0px'><a href='/add_review/{{book.id}}'>{{book.title}}</a></h2>
      Author: {{book.author}}<br>
      {%for review in reviews%}
        {%if review.book_id == book.id%}
          {%for user in users%}
            {%if review.user_id == user.id%}
              <a href="/user_reviews/{{user.id}}">{{user.first_name}}</a> says:
            {%endif%}
          {%endfor%}
          {{review.review}}<br>
          Rating: {{review.rating}} stars<br>
          posted on: {{review.created_at}}

          {%if review.user.id == request.session.user.id%}
          <a href="/delete_review/{{review.id}}"><button>Delete Review</button></a>
          {%endif%}

          <br><br>

        {%endif%}
      {%endfor%}
    {%endfor%}<br>

    <h2>Other Books with Reviews</h2>
    <div style="width: 300px; height: 100px; overflow-y: scroll;">
      {%for book in books2%}
        <a href="/add_review/{{book.id}}">{{book.title}}</a><br>
      {%endfor%}
    </div>
  </body>
</html>

book_review3/apps/reviews/templates/reviews/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Book Reviews</title>
  </head>
  <body>
    <h1>Welcome!</h1>
    <h2>Register</h2>
    {%if messages%}
      {%for message in messages%}
        <p>{{message}}</p>
      {%endfor%}
    {%endif%}
    <form action="/register" method="post">
      {%csrf_token%}
      First Name: <input type="text" name="first_name" value=""><br>
      Alias: <input type="text" name="alias" value=""><br>
      Email: <input type="text" name="email" value=""><br>
      Password: <input type="password" name="password" value=""><br>
      *Password should be at least 8 characters<br>
      Confirm Password: <input type="password" name="confirm_pw" value=""><br><br>
      <input type="submit" name="" value="Register"><br>
    </form>
    <h1>Login</h1>
    <form action="/login" method="post">
      {%csrf_token%}
      Email: <input type="text" name="email" value=""><br>
      Password: <input type="password" name="password" value=""><br><br>
      <input type="submit" name="" value="Login">
    </form>
  </body>
</html>

book_review3/apps/reviews/templates/reviews/user_reviews.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h3>User Alias: {{user.alias}} </h3>
    <a href="/success"><button>Home</button></a><a href="/add_book_review"><button>
    Add Book and Review</button></a>
    <a href="/logout"><button>
    Log out</button></a>

    <br>

    Name: {{user.first_name}}<br>
    Email: {{user.email}}<br>
    Total Reviews: {{count}} <br><br><br>
    Posted Reviews on the following books:<br>

    {%for review in reviews%}
      <a href="/add_review/{{review.book.id}}">{{review.book.title}}</a><br>
      <a href="/add_review/{{review.book__id}}">{{review.book__title}}</a><br>
    {%endfor%}<br>
    {%for review in review_set%}
      asdfasdf
    {%endfor%}
  </body>
</html>